# Generated by Django 4.2.7 on 2026-01-31 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("creative_url", models.URLField(blank=True, null=True)),
                ("status", models.CharField(default="active", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ads",
            },
        ),
        migrations.CreateModel(
            name="AdGroup",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("status", models.CharField(default="active", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ad_groups",
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("platform", models.CharField(max_length=100)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("status", models.CharField(default="active", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "campaigns",
            },
        ),
        migrations.CreateModel(
            name="Metric",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("impressions", "Impressions"),
                            ("clicks", "Clicks"),
                            ("cost", "Cost"),
                            ("conversions", "Conversions"),
                            ("revenue", "Revenue"),
                        ],
                        max_length=50,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=15)),
                ("platform", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="core.ad",
                    ),
                ),
                (
                    "ad_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="core.adgroup",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="core.campaign",
                    ),
                ),
            ],
            options={
                "db_table": "metrics",
            },
        ),
        migrations.CreateModel(
            name="Insight",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("best_campaign", "Best Performing Campaign"),
                            ("underperforming_ad", "Underperforming Ad"),
                            ("budget_inefficiency", "Budget Inefficiency"),
                            ("anomaly_detected", "Anomaly Detected"),
                        ],
                        max_length=100,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("entity_id", models.CharField(max_length=255)),
                ("entity_type", models.CharField(max_length=50)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "insights",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["type", "severity"], name="insights_type_ea4ba2_idx"
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="insights_entity__231aa2_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="insights_created_87d375_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["platform", "status"], name="campaigns_platfor_c85502_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["start_date", "end_date"], name="campaigns_start_d_5c7483_idx"
            ),
        ),
        migrations.AddField(
            model_name="adgroup",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ad_groups",
                to="core.campaign",
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="ad_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ads",
                to="core.adgroup",
            ),
        ),
        migrations.AddIndex(
            model_name="metric",
            index=models.Index(
                fields=["campaign", "date", "metric_type"],
                name="metrics_campaig_292cb7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="metric",
            index=models.Index(
                fields=["date", "platform"], name="metrics_date_6d0b90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="metric",
            index=models.Index(
                fields=["ad_group", "date"], name="metrics_ad_grou_2868d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="metric",
            index=models.Index(fields=["ad", "date"], name="metrics_ad_id_201e16_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="metric",
            unique_together={
                ("campaign", "ad_group", "ad", "date", "metric_type", "platform")
            },
        ),
        migrations.AddIndex(
            model_name="adgroup",
            index=models.Index(
                fields=["campaign", "status"], name="ad_groups_campaig_507eaf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ad",
            index=models.Index(
                fields=["ad_group", "status"], name="ads_ad_grou_ec70e4_idx"
            ),
        ),
    ]
